theme: jekyll-theme-cayman
title: BAT donation homepage
description: donenme sus BAT!!!!
author: Pandalft

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pandalft.github.io/" # the base hostname & protocol for your site
url: "https://pandalft.github.io/" # the base hostname & protocol for your site
github_username:  Pandalft

# Build settings
markdown: kramdown

include: [".well-known"]
